---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVjCCAf2gAwIBAgIQL5D0yWLOb+TnxFXyuz3GHDAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMTExMDMwMjA0MDBaFw0zMTExMDEwMjA0
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEITAk2gqCqNRRZrlswQHB5oJw3CfqTQ2XH8KbnVMkHL7/e6Zg1NiYuaef
          UGcw3H1sL1z8otv6aEOJfqhpFp6l5aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCCx1Gr1f+Lss9w6eujVMbMnXuZ5K6yiCnA3KGyRdue0jjAKBggqhkjOPQQD
          AgNHADBEAiAqBbwN6GcA6OI6WQSa2lvknPvb0WETWvGnJegf3cAcCQIgXQkOQ022
          ElvUIZ3FQO+bvH7zvj/tHOq5LHuJc6ROKLI=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfigAwIBAgIRAJPy+hr5mIxc8pMhItFrfEowCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjExMTAzMDIwNDAwWhcNMzExMTAxMDIwNDAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BA9rKpSsh6BIcxiGEPdFRTpPX1zjv7i8oA1o+GvX6T/sv4Z2U89b0ro1u6D+P/Ar
          x/tuVlydthrSTi4w9G9+mTajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          ddP6FHwJNBuRVdjbAg74unZHsBRgmtPA807auwIOsDwwCgYIKoZIzj0EAwIDRwAw
          RAIgF9rWgd2bWhU/PvvDBvX8u5MsOMW/5KhndFmc5Su60NYCIBeXtgsQPPGqHgn9
          k34W42uXOWf/6FIZ/mpsUXOvKmgo
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
